defaultContentLanguage = "vi"
defaultContentLanguageInSubdir = false
enableEmoji = true

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    weight = 10
  [languages.en]
    languageName = "English"
    weight = 20

[module]
  [module.hugoVersion]
    extended = true
    min = "0.140.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false